version: "3.7"

services:
    ls:
        build: .
        container_name: LinkShort
        ports: 
            - "5002:5002"
        restart: always
        volumes:
            - server-logs:/logs

volumes: 
    server-logs:
        external: true  
        name: server-logs