version: "3.7"

services:
    redis_db:
        image: redis
        container_name: Linkshort-db
        ports:
            - "6379:6379"
        restart: always
        volumes:
            - ./data:/data

    server:
        build: .
        container_name: LinkShort
        ports:
            - "5002:5002"
        restart: always
        depends_on:
            - redis_db
        links:
            - "redis_db:redis_db"
